# Generated by Django 4.0.4 on 2022-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_date_project_description_project_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectMembers',
            field=models.ManyToManyField(to='users.user'),
        ),
    ]
