# Generated by Django 4.0.4 on 2022-05-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_project_projectmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='users.user'),
        ),
    ]
