# Generated by Django 4.0.4 on 2022-05-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Orbi_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
