# Generated by Django 4.0.4 on 2022-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_orbi_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='Journal',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='Year',
        ),
        migrations.AddField(
            model_name='publication',
            name='Citation',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='Link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
