# Generated by Django 4.0.4 on 2022-05-25 08:42

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Image_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectMembers',
            new_name='project_members',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='Citation',
            new_name='citation',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='Link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='UserId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='Link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='UserId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Biography',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Orbi_url',
            new_name='orbi_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=75, size=[117, 117], upload_to=users.models.wrapper),
        ),
    ]
