# Generated by Django 4.0.4 on 2022-05-25 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_date_project_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
