# Generated by Django 4.0.4 on 2022-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_date_project_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orbi_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
