# Generated by Django 4.0.4 on 2022-05-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_publication_user_id'),
        ('users', '0015_alter_user_orbi_url'),
    ]

    operations = [
    ]
