# Generated by Django 4.0.4 on 2022-05-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20220525_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='summary',
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(),
        ),
    ]
