# Generated by Django 4.0.4 on 2022-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20220525_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
