# Generated by Django 4.0.4 on 2022-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_summary_alter_publication_citation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
