# Generated by Django 4.0.4 on 2022-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
