# Generated by Django 4.0.4 on 2022-05-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_socialnetwork_link'),
        ('users', '0019_alter_user_summary'),
    ]

    operations = [
    ]
