# Generated by Django 4.0.4 on 2022-05-26 08:15

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20220526_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=-1, size=[500, 500], upload_to=users.models.wrapper),
        ),
    ]
