# Generated by Django 4.0.4 on 2022-05-26 08:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner_url',
            field=models.ImageField(blank=True, upload_to=users.models.partners),
        ),
    ]
