# Generated by Django 4.0.4 on 2022-05-26 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='projects_collab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='coordiantors',
            field=models.ManyToManyField(blank=True, related_name='projects_coordinated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='projects_research', to=settings.AUTH_USER_MODEL),
        ),
    ]
