# Generated by Django 4.0.4 on 2022-05-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_project_collaborators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='coordiantors',
            new_name='coordinators',
        ),
    ]
