# Generated by Django 4.0.4 on 2022-05-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_publication_options'),
        ('users', '0027_rename_coordiantors_project_coordinators'),
    ]

    operations = [
    ]
