# Generated by Django 4.0.4 on 2022-05-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_merge_20220527_0735'),
        ('users', '0028_merge_20220527_0821'),
    ]

    operations = [
    ]
