# Generated by Django 4.0.4 on 2022-05-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_merge_20220527_0827'),
        ('users', '0029_merge_20220527_0838'),
    ]

    operations = [
    ]
