# Generated by Django 4.0.4 on 2022-05-28 07:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_merge_20220527_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, upload_to=users.models.partners)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, upload_to=users.models.partners)),
            ],
        ),
    ]
