# Generated by Django 4.0.4 on 2022-05-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_event_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
